########################################################
###datasource
########################################################
spring:
  profiles: test
  datasource:
    dbwwwjebecom:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://test.3000g.net:3306/dbwwwjebecom?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: xiaowei
      testWhileIdle: true
      max-active: 20    #连接数: 最大值
      max-idle: 2       #连接数: 最大空闲值, 连接池可以慢慢将已经用不到的连接慢慢释放一部分，一直减少到maxIdle为止, 0时无限制
      min-idle: 2       #连接数: 最小空闲值, 当空闲的连接数少于阀值时,连接池就会预申请去一些连接
      initial-size: 2   #连接数: 连接池启动时创建的连接数初始值

    lvzheng:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://test.3000g.net:3306/lvzheng?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: xiaowei
      testWhileIdle: true
      max-active: 5     #连接数: 最大值
      max-idle: 1       #连接数: 最大空闲值, 连接池可以慢慢将已经用不到的连接慢慢释放一部分，一直减少到maxIdle为止, 0时无限制
      min-idle: 1       #连接数: 最小空闲值, 当空闲的连接数少于阀值时,连接池就会预申请去一些连接
      initial-size: 1   #连接数: 连接池启动时创建的连接数初始值

    enterprise:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://test.3000g.net:3306/enterprise?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: xiaowei
      testWhileIdle: true
      max-active: 5     #连接数: 最大值
      max-idle: 1       #连接数: 最大空闲值, 连接池可以慢慢将已经用不到的连接慢慢释放一部分，一直减少到maxIdle为止, 0时无限制
      min-idle: 1       #连接数: 最小空闲值, 当空闲的连接数少于阀值时,连接池就会预申请去一些连接
      initial-size: 1   #连接数: 连接池启动时创建的连接数初始值